# Generated by Django 5.2 on 2025-06-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        ('parser_controler', '0007_parsinginfo_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesBlueprintText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=800)),
                ('message_title', models.CharField(max_length=120)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sended', 'Sended'), ('readed', 'Readed'), ('error', 'Error')], default='sended', max_length=10)),
                ('parsing_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parser_controler.parsinginfo')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.messagesblueprinttext')),
            ],
        ),
    ]
