# Generated by Django 5.2 on 2025-04-24 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_controler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Список ключевых слов, например: ['Python', 'Remote']", null=True, size=None, verbose_name='Keywords')),
                ('location', models.CharField(blank=True, help_text="Страна или город, например: 'Germany'", max_length=255, null=True, verbose_name='Location')),
                ('limit', models.PositiveIntegerField(default=50, help_text='Максимум профилей к возврату', verbose_name='Limit')),
                ('start_page', models.PositiveIntegerField(default=1, help_text='С какой страницы начать парсинг', verbose_name='Start Page')),
                ('end_page', models.PositiveIntegerField(default=5, help_text='До какой страницы дойти включительно', verbose_name='End Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parser Request',
                'verbose_name_plural': 'Parser Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
