# Generated by Django 5.2 on 2025-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_controler', '0002_parserrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsinginfo',
            name='profile_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile URL'),
        ),
    ]
