# Generated by Django 5.2 on 2025-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_controler', '0003_parsinginfo_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', help_text='Текущий статус парсинга', max_length=20, verbose_name='Status'),
        ),
    ]
