# Generated by Django 5.2 on 2025-05-04 21:27

import authorization.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authorization.managers.CustomUserManager()),
            ],
        ),
    ]
