# Generated by Django 5.2 on 2025-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Parsing Info',
                'verbose_name_plural': 'Parsing Info',
                'ordering': ['company_name', 'full_name'],
            },
        ),
    ]
