# Generated by Django 5.2 on 2025-06-10 22:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_controler', '0004_parserrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsinginfo',
            options={'ordering': ['-created_at', 'company_name', 'full_name'], 'verbose_name': 'Parsing Info', 'verbose_name_plural': 'Parsing Info'},
        ),
        migrations.AddField(
            model_name='parserrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parserrequest',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrequest',
            name='emails_extracted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrequest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parserrequest',
            name='profiles_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parsinginfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parsinginfo',
            name='parser_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='parser_controler.parserrequest'),
        ),
    ]
