# Generated by Django 5.2 on 2025-06-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_controler', '0005_alter_parsinginfo_options_parserrequest_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsinginfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parsing Info', 'verbose_name_plural': 'Parsing Info'},
        ),
        migrations.AddField(
            model_name='parserrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsinginfo',
            name='page_found',
            field=models.IntegerField(blank=True, help_text='Page number where profile was found', null=True),
        ),
        migrations.AddField(
            model_name='parsinginfo',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Keywords used to find this profile', null=True),
        ),
        migrations.AddField(
            model_name='parsinginfo',
            name='search_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parsinginfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='current_page',
            field=models.IntegerField(blank=True, help_text='Current page being processed', null=True),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='emails_extracted',
            field=models.IntegerField(default=0, help_text='Emails successfully extracted'),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='end_page',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='keywords',
            field=models.TextField(default='["linkedin"]', help_text='Keywords to search for (JSON array or comma-separated)'),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='location',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='profiles_found',
            field=models.IntegerField(default=0, help_text='Total profiles found'),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='start_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='parserrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='parser_request',
            field=models.ForeignKey(blank=True, help_text='The parser request that found this profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='parser_controler.parserrequest'),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='parsinginfo',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='parsinginfo',
            unique_together={('parser_request', 'full_name', 'company_name')},
        ),
    ]
