# Generated by Django 5.2 on 2025-06-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_controler', '0008_alter_parsinginfo_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User assigned to this parser request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parser_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
