# Generated by Django 5.2 on 2025-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_time_paid',
            field=models.BooleanField(default=False),
        ),
    ]
